version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "prisma-runtime-protection"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10qrl9wgc1thr"
s3_prefix = "prisma-runtime-protection"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
